### PR TITLE
Unowned self reference crashed on iOS 13

### LINKED ISSUE #1987: Crash with Xcode 11.4 b1
Hi,

_Eureka version: 5.2.0 via Pod._

There is a crash with Xcode 11.4 b1, seem to be related with `[unowned self]` in the code.

I know it's just a beta, but this bug(?) needs to be watched.

### LINKED ISSUE #1988: Xcode 11.4, error: Segmentation fault: 11 (in target 'Eureka' from project 'Eureka')
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source

homebrew

* `which carthage`:

/usr/local/bin/carthage

* `carthage version`: 
0.34.0

* `xcodebuild -version`: 

Xcode 11.4
Build version 11N111s

* Are you using `--no-build`? 

No

* Are you using `--no-use-binaries`? 

Yes

* Are you using `--use-submodules`? 

No

* Are you using `--cache-builds`? 

No

* Are you using `--new-resolver`? 

No

**Cartfile**
```
github "xmartlabs/Eureka" "master"
```

**Carthage Output**
```
/usr/bin/xcrun xcodebuild -workspace /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Eureka.xcworkspace -scheme Eureka -configuration Release -derivedDataPath /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/15/kgbxrq_d6r179r0fdtwvj4c80000gn/T/Eureka SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka)2020-02-08 21:48:06.842 xcodebuild[59701:622428] [MT] PluginLoading: Required plug-in compatibility UUID 31056F1F-412A-4C99-8092-C3B5AA79148C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Command line invocation:
    /Users/bob/Applications/Xcode-beta.app/Contents/Developer/usr/bin/xcodebuild -workspace /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Eureka.xcworkspace -scheme Eureka -configuration Release -derivedDataPath /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/15/kgbxrq_d6r179r0fdtwvj4c80000gn/T/Eureka SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO

User defaults from command line:
    IDEArchivePathOverride = /var/folders/15/kgbxrq_d6r179r0fdtwvj4c80000gn/T/Eureka
    IDEDerivedDataPathOverride = /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos13.4
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
CreateBuildDirectory /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    builtin-create-build-directory /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath

CreateBuildDirectory /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    builtin-create-build-directory /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath

CreateBuildDirectory /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/InstallationBuildProductsLocation (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    builtin-create-build-directory /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/InstallationBuildProductsLocation

SymLink /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos/Eureka.framework /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Eureka.framework (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    /bin/ln -sfh /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Eureka.framework /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos/Eureka.framework

MkDir /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Eureka.framework (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    /bin/mkdir -p /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Eureka.framework

MkDir /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Eureka.framework/Headers (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    /bin/mkdir -p /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Eureka.framework/Headers

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/all-product-headers.yaml (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/all-product-headers.yaml

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka.hmap (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka.hmap

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-project-headers.hmap (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-project-headers.hmap

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-own-target-headers.hmap (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-own-target-headers.hmap

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-generated-files.hmap (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-generated-files.hmap

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-all-target-headers.hmap (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-all-target-headers.hmap

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-all-non-framework-target-headers.hmap (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-all-non-framework-target-headers.hmap

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/unextended-module.modulemap (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/unextended-module.modulemap

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/unextended-module-overlay.yaml (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/unextended-module-overlay.yaml

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/module.modulemap (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/module.modulemap

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Eureka.SwiftFileList (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Eureka.SwiftFileList

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Eureka.LinkFileList (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Eureka.LinkFileList

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Eureka-OutputFileMap.json (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Eureka-OutputFileMap.json

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Eureka.SwiftFileList (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Eureka.SwiftFileList

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Eureka.LinkFileList (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Eureka.LinkFileList

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Eureka-OutputFileMap.json (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Eureka-OutputFileMap.json

WriteAuxiliaryFile /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources/Eureka_vers.c (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    write-file /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources/Eureka_vers.c

Ditto /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/module.modulemap /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Eureka.framework/Modules/module.modulemap (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/module.modulemap /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Eureka.framework/Modules

CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    export DEVELOPER_DIR=/Users/bob/Applications/Xcode-beta.app/Contents/Developer
    export SDKROOT=/Users/bob/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
    /Users/bob/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Eureka -O -whole-module-optimization -enforce-exclusivity=checked -Xfrontend -disable-swift3-objc-inference @/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Eureka.SwiftFileList -sdk /Users/bob/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -target armv7-apple-ios9.0 -g -module-cache-path /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/ModuleCache.noindex -Xfrontend -serialize-debugging-options -application-extension -embed-bitcode -swift-version 5 -I /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos -F /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos -c -num-threads 4 -output-file-map /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Eureka-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Eureka.swiftmodule -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-generated-files.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-own-target-headers.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-project-headers.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources-normal/armv7 -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources/armv7 -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Eureka-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/unextended-module-overlay.yaml -working-directory /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka

CompileSwift normal armv7 (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    /Users/bob/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -emit-bc /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PickerInlineRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PopoverSelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/SelectableRowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SegmentedRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/LabelRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleRequired.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Controllers/SelectorAlertController.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/RowControllerType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PushRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/FieldRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Controllers/SelectorViewController.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/DecimalFormatter.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Validation.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Core.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Form.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleClosure.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SwitchRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PickerInputRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleLength.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DoublePickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/MultipleSelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/AlertRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/ActionSheetRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/PresenterRowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/TextAreaRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Cell.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DatePickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleEqualsToRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/CellType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DoublePickerInputRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/FieldsRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Helpers.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleURL.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/RowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleRegExp.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/DateInlineFieldRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/NavigationAccessoryView.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/StepperRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/AlertOptionsRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DateInlineRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/ButtonRowWithPresent.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/SwipeActions.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/RowProtocols.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/CheckRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/HeaderFooterView.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/SelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleRange.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SelectableRows/ListCheckRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SliderRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/OptionsRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/ButtonRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/SelectableSection.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/InlineRowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleEmail.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/TriplePickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Operators.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/Protocols.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Section.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DateRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/BaseRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/TriplePickerInputRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Row.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/GenericMultipleSelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Controllers/MultipleSelectorViewController.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/DateFieldRow.swift -supplementary-output-file-map /var/folders/15/kgbxrq_d6r179r0fdtwvj4c80000gn/T/supplementaryOutputs-6ea0f4 -target armv7-apple-ios9.0 -enable-objc-interop -sdk /Users/bob/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -I /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos -F /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos -application-extension -g -import-underlying-module -module-cache-path /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -O -disable-swift3-objc-inference -serialize-debugging-options -Xcc -working-directory -Xcc /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-generated-files.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-own-target-headers.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-project-headers.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources-normal/armv7 -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources/armv7 -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources -Xcc -ivfsoverlay -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/unextended-module-overlay.yaml -module-name Eureka -num-threads 4 -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/PickerInlineRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/PopoverSelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/SelectableRowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/SegmentedRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/LabelRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RuleRequired.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/SelectorAlertController.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RowControllerType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/PushRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/FieldRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/SelectorViewController.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/DecimalFormatter.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Validation.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Core.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Form.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RuleClosure.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/SwitchRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/PickerInputRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RuleLength.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/DoublePickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/MultipleSelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/AlertRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/ActionSheetRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/PresenterRowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/TextAreaRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Cell.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/DatePickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RuleEqualsToRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/CellType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/DoublePickerInputRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/PickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/FieldsRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Helpers.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RuleURL.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RuleRegExp.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/DateInlineFieldRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/NavigationAccessoryView.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/StepperRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/AlertOptionsRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/DateInlineRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/ButtonRowWithPresent.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/SwipeActions.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RowProtocols.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/CheckRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/HeaderFooterView.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/SelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RuleRange.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/ListCheckRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/SliderRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/OptionsRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/ButtonRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/SelectableSection.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/InlineRowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/RuleEmail.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/TriplePickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Operators.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Protocols.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Section.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/DateRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/BaseRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/TriplePickerInputRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/Row.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/GenericMultipleSelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/MultipleSelectorViewController.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/armv7/DateFieldRow.bc
Command CompileSwift failed with a nonzero exit code

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    export DEVELOPER_DIR=/Users/bob/Applications/Xcode-beta.app/Contents/Developer
    export SDKROOT=/Users/bob/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
    /Users/bob/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Eureka -O -whole-module-optimization -enforce-exclusivity=checked -Xfrontend -disable-swift3-objc-inference @/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Eureka.SwiftFileList -sdk /Users/bob/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -target arm64-apple-ios9.0 -g -module-cache-path /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/ModuleCache.noindex -Xfrontend -serialize-debugging-options -application-extension -embed-bitcode -swift-version 5 -I /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos -F /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos -c -num-threads 4 -output-file-map /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Eureka-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Eureka.swiftmodule -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-generated-files.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-own-target-headers.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-project-headers.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources-normal/arm64 -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources/arm64 -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Eureka-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/unextended-module-overlay.yaml -working-directory /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'Eureka' from project 'Eureka')
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal 11 (use -v to see invocation)

CompileSwift normal arm64 (in target 'Eureka' from project 'Eureka')
    cd /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka
    /Users/bob/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -emit-bc /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PickerInlineRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PopoverSelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/SelectableRowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SegmentedRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/LabelRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleRequired.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Controllers/SelectorAlertController.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/RowControllerType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PushRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/FieldRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Controllers/SelectorViewController.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/DecimalFormatter.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Validation.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Core.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Form.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleClosure.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SwitchRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PickerInputRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleLength.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DoublePickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/MultipleSelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/AlertRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/ActionSheetRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/PresenterRowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/TextAreaRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Cell.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DatePickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleEqualsToRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/CellType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DoublePickerInputRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/FieldsRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Helpers.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleURL.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/RowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleRegExp.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/DateInlineFieldRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/NavigationAccessoryView.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/StepperRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/AlertOptionsRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DateInlineRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/ButtonRowWithPresent.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/SwipeActions.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/RowProtocols.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/CheckRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/HeaderFooterView.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/SelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleRange.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SelectableRows/ListCheckRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SliderRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/OptionsRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/ButtonRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/SelectableSection.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/InlineRowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleEmail.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/TriplePickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Operators.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/Protocols.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Section.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DateRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/BaseRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/TriplePickerInputRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Row.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/GenericMultipleSelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Controllers/MultipleSelectorViewController.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/DateFieldRow.swift -supplementary-output-file-map /var/folders/15/kgbxrq_d6r179r0fdtwvj4c80000gn/T/supplementaryOutputs-35bb9d -target arm64-apple-ios9.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Users/bob/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -I /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos -F /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos -application-extension -g -import-underlying-module -module-cache-path /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -O -disable-swift3-objc-inference -serialize-debugging-options -Xcc -working-directory -Xcc /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-generated-files.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-own-target-headers.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-project-headers.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources-normal/arm64 -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources/arm64 -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources -Xcc -ivfsoverlay -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/unextended-module-overlay.yaml -module-name Eureka -num-threads 4 -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PickerInlineRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PopoverSelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SelectableRowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SegmentedRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/LabelRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleRequired.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SelectorAlertController.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RowControllerType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PushRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/FieldRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SelectorViewController.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DecimalFormatter.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Validation.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Core.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Form.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleClosure.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SwitchRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PickerInputRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleLength.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DoublePickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/MultipleSelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/AlertRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/ActionSheetRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PresenterRowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/TextAreaRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Cell.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DatePickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleEqualsToRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/CellType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DoublePickerInputRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/FieldsRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Helpers.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleURL.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleRegExp.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DateInlineFieldRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/NavigationAccessoryView.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/StepperRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/AlertOptionsRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DateInlineRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/ButtonRowWithPresent.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SwipeActions.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RowProtocols.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/CheckRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/HeaderFooterView.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleRange.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/ListCheckRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SliderRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/OptionsRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/ButtonRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SelectableSection.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/InlineRowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleEmail.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/TriplePickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Operators.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Protocols.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Section.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DateRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/BaseRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/TriplePickerInputRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Row.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/GenericMultipleSelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/MultipleSelectorViewController.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DateFieldRow.bc
Stack dump:
0.	Program arguments: /Users/bob/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -emit-bc /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PickerInlineRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PopoverSelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/SelectableRowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SegmentedRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/LabelRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleRequired.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Controllers/SelectorAlertController.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/RowControllerType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PushRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/FieldRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Controllers/SelectorViewController.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/DecimalFormatter.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Validation.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Core.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Form.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleClosure.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SwitchRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PickerInputRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleLength.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DoublePickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/MultipleSelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/AlertRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/ActionSheetRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/PresenterRowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/TextAreaRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Cell.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DatePickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleEqualsToRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/CellType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DoublePickerInputRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/PickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/FieldsRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Helpers.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleURL.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/RowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleRegExp.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/DateInlineFieldRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/NavigationAccessoryView.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/StepperRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/AlertOptionsRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DateInlineRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/ButtonRowWithPresent.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/SwipeActions.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/RowProtocols.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/CheckRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/HeaderFooterView.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/SelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleRange.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SelectableRows/ListCheckRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/SliderRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/OptionsRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/ButtonRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/SelectableSection.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/InlineRowType.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Validations/RuleEmail.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/TriplePickerRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Operators.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/Protocols.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Section.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/DateRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/BaseRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/TriplePickerInputRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/Row.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/GenericMultipleSelectorRow.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Controllers/MultipleSelectorViewController.swift /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Rows/Common/DateFieldRow.swift -supplementary-output-file-map /var/folders/15/kgbxrq_d6r179r0fdtwvj4c80000gn/T/supplementaryOutputs-35bb9d -target arm64-apple-ios9.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Users/bob/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -I /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos -F /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos -application-extension -g -import-underlying-module -module-cache-path /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -O -disable-swift3-objc-inference -serialize-debugging-options -Xcc -working-directory -Xcc /Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-generated-files.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-own-target-headers.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Eureka-project-headers.hmap -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources-normal/arm64 -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources/arm64 -Xcc -I/Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/DerivedSources -Xcc -ivfsoverlay -Xcc /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/unextended-module-overlay.yaml -module-name Eureka -num-threads 4 -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PickerInlineRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PopoverSelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SelectableRowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SegmentedRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/LabelRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleRequired.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SelectorAlertController.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RowControllerType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PushRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/FieldRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SelectorViewController.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DecimalFormatter.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Validation.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Core.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Form.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleClosure.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SwitchRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PickerInputRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleLength.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DoublePickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/MultipleSelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/AlertRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/ActionSheetRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PresenterRowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/TextAreaRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Cell.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DatePickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleEqualsToRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/CellType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DoublePickerInputRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/PickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/FieldsRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Helpers.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleURL.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleRegExp.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DateInlineFieldRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/NavigationAccessoryView.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/StepperRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/AlertOptionsRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DateInlineRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/ButtonRowWithPresent.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SwipeActions.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RowProtocols.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/CheckRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/HeaderFooterView.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleRange.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/ListCheckRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SliderRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/OptionsRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/ButtonRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/SelectableSection.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/InlineRowType.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/RuleEmail.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/TriplePickerRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Operators.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Protocols.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Section.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DateRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/BaseRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/TriplePickerInputRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/Row.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/GenericMultipleSelectorRow.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/MultipleSelectorViewController.bc -o /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/Eureka.build/Release-iphoneos/Eureka.build/Objects-normal/arm64/DateFieldRow.bc 
1.	Apple Swift version 5.2 (swiftlang-1103.0.22 clang-1103.0.22)
2.	While emitting IR SIL function "@$s6Eureka7RowTypePA2A04BaseB0CRbzrlE15onCellSelectionyxy0F0Qz_xtcFyycfU_AA06ButtonB2OfCySSG_Tg5".
 for expression at [/Users/bob/Documents/iosladderProjects/BearFree/Carthage/Checkouts/Eureka/Source/Core/RowType.swift:238:35 - line:238:82] RangeText="{ [unowned self] in  callback(self.cell, self) "
0  swift                    0x00000001120509b3 PrintStackTraceSignalHandler(void*) + 51
1  swift                    0x0000000112050170 SignalHandler(int) + 352
2  libsystem_platform.dylib 0x00007fff6e71d42d _sigtramp + 29
3  libsystem_platform.dylib 0x00007ffee237e310 _sigtramp + 1942359808
4  swift                    0x000000010db7f522 swift::SILInstructionVisitor<(anonymous namespace)::IRGenSILFunction, void>::visit(swift::SILInstruction*) + 94338
5  swift                    0x000000010db64b83 swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 9027
6  swift                    0x000000010da14de6 swift::irgen::IRGenerator::emitLazyDefinitions() + 8822
7  swift                    0x000000010db3f20b swift::performIRGeneration(swift::IRGenOptions&, swift::ModuleDecl*, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::LLVMContext&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, llvm::GlobalVariable**) + 1979
8  swift                    0x000000010d92bade performCompileStepsPostSILGen(swift::CompilerInstance&, swift::CompilerInvocation&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, bool, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, bool, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 4126
9  swift                    0x000000010d9227f5 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 62917
10 swift                    0x000000010d893283 main + 1299
11 libdyld.dylib            0x00007fff6e5247fd start + 1
12 libdyld.dylib            0x0000000000000107 start + 2444081419
error: Segmentation fault: 11 (in target 'Eureka' from project 'Eureka')

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(3 failures)
```

**Actual outcome**

```
$ carthage update --platform ios
*** Fetching Eureka
*** Checking out Eureka at "567d4e172fa3f50952eb2462cb7a9785403530f2"
*** xcodebuild output can be found in /var/folders/15/kgbxrq_d6r179r0fdtwvj4c80000gn/T/carthage-xcodebuild.dmckQi.log
*** Building scheme "Eureka" in Eureka.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/Shared/testobj/Carthage/Checkouts/Eureka/Eureka.xcworkspace -scheme Eureka -configuration Release -derivedDataPath /Users/bob/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11N111s/Eureka/567d4e172fa3f50952eb2462cb7a9785403530f2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/15/kgbxrq_d6r179r0fdtwvj4c80000gn/T/Eureka SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/Shared/testobj/Carthage/Checkouts/Eureka)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/15/kgbxrq_d6r179r0fdtwvj4c80000gn/T/carthage-xcodebuild.dmckQi.log
```

**Expected outcome**

```
$ carthage update --platform ios
$ echo $?
0   # success
```

### LINKED ISSUE #1999: Eureka Crash IOS 13.4 beta 4, Xcode 11.4 beta 3
I am still experience a crash in iOS 13.4 beta 4 using Xcode 11.4 beta 3.  I have isolated the crash to .cellSetup, .cellUpdate, .onCellSelection where { cell, row in } is called in RowType.Swift. 

I commented out the aforementioned and Eureka was able to load and functioned as expected without these essential features.

The issue was closed but has persisted throughout the 13.4 beta and has not been resolved.  I do not believe it is a compiler error in the beta but some modification that results from the transition to Swift 5.2.

**.cellUpdate**

> public var cell: Cell! {
        return _cell ?? {
            let result = cellProvider.makeCell(style: self.cellStyle)
            result.row = self
            result.setup()
            _cell = result
            return _cell
        }()
    }

Console:

> 2020-03-08 09:58:32.892975-0700 Transit[1660:392741] [ProcessSuspension] 0x1215e1650 - ProcessAssertion::processAssertionWasInvalidated()

Trace: **#6**
>Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000180a6a978 in objc_retain ()
#1	0x0000000102555ef8 in Row.cell.getter at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:154
#2	0x0000000102556f14 in protocol witness for TypedRowType.cell.getter in conformance Row<A> ()
#3	0x000000010255d084 in closure #1 in RowType<>.cellUpdate(_:) at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/RowType.swift:216
#4	0x00000001025569fc in Row.updateCell() at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:178
#5	0x00000001024c5938 in FormViewController.tableView(_:cellForRowAt:) at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Core.swift:969
**_#6	0x00000001024c5b48 in @objc FormViewController.tableView(_:cellForRowAt:) ()_**
#7	0x0000000184f99b14 in -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] ()
#8	0x0000000184f67408 in -[UITableView _updateVisibleCellsNow:] ()
#9	0x0000000184f84458 in -[UITableView layoutSubviews] ()
#10	0x0000000185245264 in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
#11	0x00000001877c6a04 in -[CALayer layoutSublayers] ()
#12	0x00000001877ccb5c in CA::Layer::layout_if_needed(CA::Transaction*) ()
#13	0x00000001877d76a0 in CA::Layer::layout_and_display_if_needed(CA::Transaction*) ()
#14	0x0000000187720798 in CA::Context::commit_transaction(CA::Transaction*, double) ()
#15	0x000000018774a128 in CA::Transaction::commit() ()
#16	0x0000000184da9908 in _UIApplicationFlushRunLoopCATransactionIfTooLate ()
#17	0x0000000184e44a60 in __handleEventQueueInternal ()
#18	0x0000000184e3d764 in __handleHIDEventFetcherDrain ()
#19	0x0000000180cac1d4 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#20	0x0000000180cac12c in __CFRunLoopDoSource0 ()
#21	0x0000000180cab8b4 in __CFRunLoopDoSources0 ()
#22	0x0000000180ca68e4 in __CFRunLoopRun ()
#23	0x0000000180ca62a4 in CFRunLoopRunSpecific ()
#24	0x000000018ad8e38c in GSEventRunModal ()
#25	0x0000000184db0bf4 in UIApplicationMain ()
#26	0x00000001009e0854 in main at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Transit/AppDelegate.swift:10
#27	0x0000000180b2d8f0 in start ()

**.cellSetup**
>@discardableResult
    public func cellSetup(_ callback: @escaping ((_ cell: Cell, _ row: Self) -> Void)) -> Self {
        callbackCellSetup = { [unowned self] (cell: Cell) in  callback(cell, self) }
        return self
    }

Console
> Fatal error: Attempted to read an unowned reference but object 0x28092ad30 was already deallocated2020-03-08 09:56:02.519456-0700 Transit[1654:391269] Fatal error: Attempted to read an unowned reference but object 0x28092ad30 was already deallocated 

Trace: **#6**
>Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000180b22d88 in __pthread_kill ()
#1	0x0000000180a3f74c in pthread_kill$VARIANT$armv81 ()
#2	0x000000018098e934 in abort ()
#3	0x000000018e3be178 in swift::fatalError(unsigned int, char const*, ...) ()
#4	0x000000018e3be2c8 in swift::swift_abortRetainUnowned(void const*) ()
#5	0x000000018e3bfbd4 in swift_unownedRetainStrong ()
**_# 6	0x000000010622d51c in closure #1 in RowType<>.cellSetup(_:) at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/RowType.swift:227_**
#7	0x000000010622d5f8 in thunk for @escaping @callee_guaranteed (@guaranteed A.Cell) -> () ()
#8	0x0000000106225e64 in thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> (@out ()) ()
#9	0x0000000106225aec in Row._cell.didset at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:148
#10	0x0000000106225cdc in Row._cell.setter ()
#11	0x00000001062260fc in closure #1 in implicit closure #1 in Row.cell.getter at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:158
#12	0x0000000106225f48 in Row.cell.getter at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:154
#13	0x00000001062261c0 in Row.baseCell.getter at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:164
#14	0x000000010618ebc0 in FormViewController.tableView(_:estimatedHeightForRowAt:) at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Core.swift:797
#15	0x000000010618ef64 in @objc FormViewController.tableView(_:estimatedHeightForRowAt:) ()
#16	0x0000000184fa5cf8 in -[UITableView _estimatedHeightForRowAtIndexPath:] ()
#17	0x0000000184fb4918 in __66-[UISectionRowData refreshWithSection:tableView:tableViewRowData:]_block_invoke ()
#18	0x0000000184fb42f0 in -[UISectionRowData refreshWithSection:tableView:tableViewRowData:] ()
#19	0x0000000184fb5c30 in -[UITableViewRowData _ensureSectionOffsetIsValidForSection:] ()
#20	0x0000000184fb92ec in -[UITableViewRowData rectForFooterInSection:heightCanBeGuessed:] ()
#21	0x0000000184fb94e0 in -[UITableViewRowData heightForTable] ()
#22	0x0000000184f5ed5c in -[UITableView _updateContentSizeSkippingContentOffsetAdjustment:] ()
#23	0x0000000184f87f78 in -[UITableView _rebuildGeometryForcingRowDataUpdate:skipContentOffsetAdjustment:updateImmediatelyIfPossible:] ()
#24	0x0000000184f85d60 in -[UITableView setLayoutMargins:] ()
#25	0x0000000184f85c48 in -[UITableView _setDefaultLayoutMargins:] ()
#26	0x0000000184f85bc0 in -[UITableView didMoveToWindow] ()
#27	0x000000018523c258 in -[UIView(Internal) _didMoveFromWindow:toWindow:] ()
#28	0x00000001851c130c in -[UIScrollView _didMoveFromWindow:toWindow:] ()
#29	0x000000018523bdd0 in -[UIView(Internal) _didMoveFromWindow:toWindow:] ()
#30	0x000000018523034c in __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke ()
#31	0x0000000185230238 in -[UIView(Hierarchy) _postMovedFromSuperview:] ()
#32	0x000000018523e974 in -[UIView(Internal) _addSubview:positioned:relativeTo:] ()
#33	0x00000001847c6428 in -[_UIParallaxDimmingView didMoveToWindow] ()
#34	0x000000018523c258 in -[UIView(Internal) _didMoveFromWindow:toWindow:] ()
#35	0x000000018523bdd0 in -[UIView(Internal) _didMoveFromWindow:toWindow:] ()
#36	0x000000018523034c in __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke ()
#37	0x0000000185230238 in -[UIView(Hierarchy) _postMovedFromSuperview:] ()
#38	0x000000018523e974 in -[UIView(Internal) _addSubview:positioned:relativeTo:] ()
#39	0x00000001847c1f7c in __53-[_UINavigationParallaxTransition animateTransition:]_block_invoke_2 ()
#40	0x0000000185237d40 in +[UIView(Animation) performWithoutAnimation:] ()
#41	0x00000001847c1918 in __53-[_UINavigationParallaxTransition animateTransition:]_block_invoke ()
#42	0x000000018523d2c8 in +[UIView(Internal) _performBlockDelayingTriggeringResponderEvents:forScene:] ()
#43	0x00000001847c138c in -[_UINavigationParallaxTransition animateTransition:] ()
#44	0x00000001847b6930 in ___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 ()
#45	0x00000001848c5d90 in +[UIInputResponderController _pinInputViewsForInputResponderController:onBehalfOfResponder:duringBlock:] ()
#46	0x00000001847b68b0 in ___UIViewControllerTransitioningRunCustomTransition_block_invoke.645 ()
#47	0x00000001852379fc in +[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] ()
#48	0x00000001847b6718 in _UIViewControllerTransitioningRunCustomTransition ()
#49	0x00000001846eb360 in -[UINavigationController _startCustomTransition:] ()
#50	0x00000001846fea08 in -[UINavigationController _startDeferredTransitionIfNeeded:] ()
#51	0x00000001846ffda8 in -[UINavigationController __viewWillLayoutSubviews] ()
#52	0x00000001846e3308 in -[UILayoutContainerView layoutSubviews] ()
#53	0x0000000185245264 in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
#54	0x00000001877c6a04 in -[CALayer layoutSublayers] ()
#55	0x00000001877ccb5c in CA::Layer::layout_if_needed(CA::Transaction*) ()
#56	0x00000001877d76a0 in CA::Layer::layout_and_display_if_needed(CA::Transaction*) ()
#57	0x0000000187720798 in CA::Context::commit_transaction(CA::Transaction*, double) ()
#58	0x000000018774a128 in CA::Transaction::commit() ()
#59	0x0000000184da9908 in _UIApplicationFlushRunLoopCATransactionIfTooLate ()
#60	0x0000000184e44a60 in __handleEventQueueInternal ()
#61	0x0000000184e3d764 in __handleHIDEventFetcherDrain ()
#62	0x0000000180cac1d4 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#63	0x0000000180cac12c in __CFRunLoopDoSource0 ()
#64	0x0000000180cab8b4 in __CFRunLoopDoSources0 ()
#65	0x0000000180ca68e4 in __CFRunLoopRun ()
#66	0x0000000180ca62a4 in CFRunLoopRunSpecific ()
#67	0x000000018ad8e38c in GSEventRunModal ()
#68	0x0000000184db0bf4 in UIApplicationMain ()
#69	0x00000001046e4838 in main at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Transit/AppDelegate.swift:10
#70	0x0000000180b2d8f0 in start ()

### PR DESCRIPTION
**Pull request by mats-claassen**
This code should be equivalent but somehow using unowned crashes the app in iOS 13.

Also when building for release the compiler crashes with a segmentation fault.

Fixes #1987 
Fixes #1999 
Fixes #1988

### CODE REVIEW

**Comment by dneykov** [comment]
@mats-claassen when these fixed will be released? I apply them manually and can confirm my app is not crashing anymore.

**Comment by LeoAiolia** [comment]
when these fixed will be released? please release as soon as possible

**Comment by mats-claassen** [comment]
Release is on its way #2011

**Comment by mffryslan** [comment]
Somehow, this fix was not enough for xcode 11.4 & iOS 13.4 GM. Still experienced a BAD_ADDRESS
@mats-claassen did you try this on the latest xcode & ios?

Added the self. reference in BaseRow and the error disappeared, should I create a PR?
```
public internal(set) var validationErrors = [ValidationError]() {
        didSet {
            guard validationErrors != oldValue else { return }
            RowDefaults.onRowValidationChanged["\(type(of: self))"]?(baseCell, self)
            self.callbackOnRowValidationChanged?()
            self.updateCell()
        }
    }
```

**Comment by mats-claassen** [comment]
@mffryslan Did you experience that in the Examples? Or can you provide code to reproduce it? I tested it on Xcode 11.4 and iOS 13.4

**Comment by vinczebalazs** [comment]
Hi!

I am not sure if it's the same issue, but getting  `EXC_BAD_ACCESS` when trying to print the value in `onChange`

Here is an example:

```
final class TestRow: Row<LabelCell>, RowType  {}
form
    ++ TestRow("test") {
        $0.title = "Title"
    }.onChange {
        print($0.value)
    }

(form.rowBy(tag: "test") as! TestRow).value = "test"
```
The crash occurs on `print($0.value)`.

- Eureka 5.2.1 
- Xcode 11.4 (11E146)
- iOS 13.4

**Comment by mats-claassen** [comment]
Hey @vinczebalazs I tried your code in the Example project and I am not getting any crash running on the simulator. Did you get that crash in the Example project?

Have you done a clean and build?

**Comment by TheWanderingCoel** [comment]
Still experiencing EXC_BAD_ACCESS with Eureka 5.2.1.
- iPhone XS Max (13.4)
- Xcode Version 11.4 beta 3 (11N132i)
- MacOS 10.15.3 (19D76)
截屏2020-04-11下午8 41 10

File: Source/Core/RowType.swift [hunk 1]
```diff
@@ -202,7 +202,7 @@ extension RowType where Self: BaseRow {
      */
     @discardableResult
     public func onChange(_ callback: @escaping (Self) -> Void) -> Self {
-        callbackOnChange = { [unowned self] in callback(self) }
+        callbackOnChange = { [weak self] in callback(self!) }
```
Comment (FM-2018-248) [inline Source/Core/RowType.swift:205]: force unwrawpping a weak self is just as bad as unowned self.  My suggestion is test the optional properly.

`[weak self] in  guard let `self` = self else { return }; callback(self)`
