### PR TITLE
Fix removeAll method in sections

### LINKED ISSUE #2048: Inconsistent state/crash when removing rows from sections with removeAll(where:)
- Environment: Eureka: 62484db23cbb1db5b90cd9e6df08dd5e976c4d8a, Xcode 11.5 and iOS 13.4.1

# Test case:

```
@testable import Eureka
import Foundation
import XCTest

class SectionTests: XCTestCase {
    func testDeletingRows() {
        let form = Form()
        var section = Section("section_01")
        form.append(section)
        
        section.append(NameRow(tag: "row_01"))
        section.append(NameRow(tag: "row_02"))
        
        section.removeAll(where: { row in row.tag == "row_01" }) // <-- Thread 1: Assertion failed: Duplicate tag row_02
        XCTAssertNotNil(form.rowBy(tag: "row_02"))
    }
}
```

# Backtrace:

> #0	0x00000001100c4330 in _swift_runtime_on_report ()
> #1	0x000000011013e0b3 in _swift_stdlib_reportFatalErrorInFile ()
> #2	0x000000010fe0073e in closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) ()
> #3	0x000000010fe00347 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) ()
> #4	0x000000010fe00927 in specialized String.withUTF8<A>(_:) ()
> #5	0x000000010fdfef4a in _assertionFailure(_:_:file:line:flags:) ()
> #6	0x000000010f94a7a7 in BaseRow.wasAddedTo(section:) at /Users/bruno/Downloads/Eureka/Source/Core/BaseRow.swift:198
> #7	0x000000010f9ae878 in Section.subscript.setter at /Users/bruno/Downloads/Eureka/Source/Core/Section.swift:267
> #8	0x000000010f9afa56 in protocol witness for MutableCollection.subscript.setter in conformance Section ()
> #9	0x000000010fdd9364 in MutableCollection.swapAt(_:_:) ()
> #10	0x000000010f9afce2 in protocol witness for MutableCollection.swapAt(_:_:) in conformance Section ()
> #11	0x000000010fe183e0 in MutableCollection._halfStablePartition(isSuffixElement:) ()
> #12	0x000000010fded891 in RangeReplaceableCollection<>.removeAll(where:) ()
> #13	0x000000010f916ad5 in SectionTests.testDeletingRows() at /Users/bruno/Downloads/Eureka/Tests/SectionTests.swift:21
> #14	0x000000010f916d7b in @objc SectionTests.testDeletingRows() ()

# Log:
```
Assertion failed: Duplicate tag row_02: file Eureka/Source/Core/BaseRow.swift, line 198
2020-06-08 10:16:09.489302+0200 xctest[4711:94968] Assertion failed: Duplicate tag row_02: file Eureka/Source/Core/BaseRow.swift, line 198
```

### PR DESCRIPTION
**Pull request by mats-claassen**
Override the `removeAll(where:)` method as it causes Duplicate Tag errors

Fixes #2048

### CODE REVIEW

File: Source/Core/Section.swift [hunk 1]
```diff
@@ -324,6 +324,21 @@ extension Section: RangeReplaceableCollection {
...
+        let indices = try kvoWrapper._allRows.enumerated().filter { (element) -> Bool in
+            return try shouldBeRemoved(element.element)
+        }.map { $0.offset }
+        var removedRows: [BaseRow] = []
+        for index in indices.reversed() {
+            removedRows.append(kvoWrapper._allRows.remove(at: index))
+        }
+        kvoWrapper.rows.removeObjects(in: removedRows)
+
+        for row in removedRows {
```
Comment (mtnbarreto) [inline Source/Core/Section.swift:337]: 1 line of code....
x.foreach { 
x.map {

File: Source/Core/Section.swift [hunk 2]
```diff
@@ -324,6 +324,21 @@ extension Section: RangeReplaceableCollection {
...
+            row.willBeRemovedFromSection()
```
Comment (mtnbarreto) [inline Source/Core/Section.swift:338]: willBeRemovedFromSection , but the rows were already removed?

**Review by mtnbarreto — CHANGES_REQUESTED** [review]

File: Source/Core/Section.swift (hunk 2 above)
Comment (mats-claassen) [reply Source/Core/Section.swift:338]: I did the same as for `removeAll(keepCapacity:`

File: Source/Core/Form.swift [hunk 3]
```diff
@@ -266,7 +266,19 @@ extension Form : RangeReplaceableCollection {
         for section in sections {
             section.willBeRemovedFromForm()
         }
+    }
+
+    public func removeAll(where shouldBeRemoved: (Section) throws -> Bool) rethrows {
+        let indices = try kvoWrapper._allSections.enumerated().filter { (element) -> Bool in
+            return try shouldBeRemoved(element.element)
```
Comment (mtnbarreto) [inline Source/Core/Form.swift:273]: I would use the short syntax  `.filter { try shouldBeRemoved($0.element )}`

File: Source/Core/Form.swift [hunk 4]
```diff
@@ -266,7 +266,19 @@ extension Form : RangeReplaceableCollection {
...
+        }.map { $0.offset }
+        var removedSections: [Section] = []
```
Comment (mtnbarreto) [inline Source/Core/Form.swift:275]: `var removedSections = [Section]()`

File: Source/Core/Section.swift [hunk 5]
```diff
@@ -324,6 +324,19 @@ extension Section: RangeReplaceableCollection {
         }
     }
 
+    public func removeAll(where shouldBeRemoved: (BaseRow) throws -> Bool) rethrows {
+        let indices = try kvoWrapper._allRows.enumerated().filter { (element) -> Bool in
+            return try shouldBeRemoved(element.element)
```
Comment (mtnbarreto) [inline Source/Core/Section.swift:329]: →

File: Source/Core/Section.swift [hunk 6]
```diff
@@ -324,6 +324,19 @@ extension Section: RangeReplaceableCollection {
...
+        }.map { $0.offset }
+        var removedRows: [BaseRow] = []
```
Comment (mtnbarreto) [inline Source/Core/Section.swift:331]: →

**Review by mtnbarreto — CHANGES_REQUESTED** [review]

**Comment by mtnbarreto** [comment]
😎

**Review by mtnbarreto — APPROVED** [review]
💪💪💪💪 groso Mathi!

**Comment by jserrafindster** [comment]
this is causing me some trouble, any idea when we will see a new released?

**Comment by jserrafindster** [comment]
Just installed 5.3.3 and im stilll having this issue 

> #0	0x0000000182c8186c in __exceptionPreprocess ()
#1	0x0000000197c9cc50 in objc_exception_throw ()
#2	0x0000000182b87000 in +[NSException raise:format:arguments:] ()
#3	0x0000000183f1b91c in -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] ()
#4	0x000000018582cb20 in -[UITableView _endCellAnimationsWithContext:] ()
#5	0x0000000185846164 in -[UITableView endUpdatesWithContext:] ()
#6	0x0000000101aab760 in FormViewController.rowsHaveBeenRemoved(_:at:) at /Users/my-user/my-app/Pods/Eureka/Source/Core/Core.swift:732
#7	0x0000000101aac72c in protocol witness for FormDelegate.rowsHaveBeenRemoved(_:at:) in conformance FormViewController ()
#8	0x0000000101b4fee0 in Section.KVOWrapper.observeValue(forKeyPath:of:change:context:) at /Users/my-user/my-app/Pods/Eureka/Source/Core/Section.swift:94
#9	0x0000000101b516fc in @objc Section.KVOWrapper.observeValue(forKeyPath:of:change:context:) ()
#10	0x0000000183fa98e0 in NSKeyValueNotifyObserver ()
#11	0x0000000183fabe70 in NSKeyValueDidChange ()
#12	0x0000000183fab8dc in -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] ()
#13	0x0000000183ee43a0 in -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] ()
#14	0x0000000183fa597c in _NSSetObjectValueAndNotify ()
#15	0x0000000101b4f150 in Section.KVOWrapper.removeAllRows() at /Users/my-user/my-app/Pods/Eureka/Source/Core/Section.swift:78
#16	0x0000000101b58920 in Section.removeAll(keepingCapacity:) at /Users/my-user/my-app/Pods/Eureka/Source/Core/Section.swift:320
#17	0x0000000100696114 in closure #1 in SettingsVC.reloadDevicesSection() at /Users/my-user/my-app/app/UI/Settings/SettingsVC.swift:369
#18	0x00000001005e07d8 in thunk for @callee_guaranteed () -> () ()
#19	0x00000001005e0830 in thunk for @escaping @callee_guaranteed () -> () ()
#20	0x0000000185b76638 in +[UIView(Animation) performWithoutAnimation:] ()
#21	0x0000000100695e08 in SettingsVC.reloadDevicesSection() at /Users/my-user/my-app/app/UI/Settings/SettingsVC.swift:368

**Comment by mats-claassen** [comment]
Please open a new issue and add details for the exception you are seeing. What is the error message? It seems you are calling `removeAll(keepingCapacity)` and not `removeAll(where:)`. So please also add some code context info
